### ISSUE TITLE
[Question] Django large CSV download timeout issue

### ISSUE THREAD

**Issue by scheung38** [jordaneremieff/aeroplane#1]
Thanks we have timeout issue of large CSV download 500 MB file or so, would FASTAPI alleviate timeout since FASTAPI supports async and Django does not? Appreciate it

**Comment by jordaneremieff** [comment]
Hi,

Django does support async via ASGI as of version 3.1. As for your timeout issues, it could be caused for a variety reasons, I would recommend asking on https://stackoverflow.com/.
